<html>
	<head>
		<title>PythonExceptionTrace-Jeffrey Zhang</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<script type="text/javascript" src="scripts/shCore.js"></script>
		<link type="text/css" href="css/main.css" rel="stylesheet"/>
		<script type="text/javascript" src="scripts/shBrushJScript.js"></script>
		<script type="text/javascript" src="scripts/shBrushPython.js"></script>
		<link type="text/css" rel="stylesheet" href="styles/shCoreDjango.css"/>
		<link type="text/css" rel="stylesheet" href="styles/shCore.css"/>
		<script type="text/javascript">SyntaxHighlighter.all();</script>
	</head>
	<body>
		<div id="wrapper">
			<header>
				<nav>
					<ul>
						<li class="first"><a title="Home" href="index.html">Home</a></li>
						<li><a title="Blog" href="diary/diary.html">Blog</a></li>
						<li class="actived"><a title="Wiki" href="index.html">Wiki</a></li>
						<li><a title="Twitter" href="https://twitter.com/GeassLei">Twitter</a></li>
						<li class="last"><a title="About Me" href="../resume/resume.html">README</a></li>
					</ul>
				</nav>
			</header>
			<article>

<h1 id="toc_1">Python Exception Trace</h1>

<p>
Python中的Exception没有记录trace的信息，当想要得到trace exception的信息时，只是简单的得到exception obj是不行的，如下:
</p>
<pre>
    def test():
        1/0

    try:
        test()
    except Exception, e:
        print e
</pre>
<p>
output
</p>
<pre>
    integer division or modulo by zero
</pre>

<p>
只得到了message的信息，而没有发生异常链的记录。
</p>

<pre>
def test():
    1/0

try:
    test()
except Exception, e:
    print "".join(traceback.format_tb(sys.exc_info()[2]))
</pre>
<p>
output
</p>
<pre>
  File "exception_demo.py", line 11, in &lt;module&gt;
    test()
  File "exception_demo.py", line 8, in test
    1/0
</pre>
<p>
基中关键的那句输出是得到exception的trace并格式化后打印输出。当需要把出错的信息输出到日志文件时，这种方式会很有效。
</p>
	</article>
	<footer>
	</footer>
	</body>
</html>
